# Project information
site_name: Grin Documentation
site_url: https://docs.grin.mw
site_author: Grin Developers
site_description: >-
  Official Grin and Grin-Wallet documentation

# Repository
repo_name: mimblewimble/docs
repo_url: https://github.com/mimblewimble/docs

# Copyright
copyright: Copyright &copy; 2016 - 2020 Grin Developers

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
    - rust

markdown_extensions:
  - admonition

nav:
  - Home: index.md
  - Getting started: getting-started.md
  - Integrations:
    - Intro: integrations/intro.md
  - Technical Details:
    - Table of Contents: technical/table-of-contents.md
    - Introduction to Mimblewimble: technical/introduction-to-mimblewimble.md
    - Grin for Bitcoiners: technical/grin-for-bitcoiners.md
    - Building Blocks:
      - Merkle Mountain Ranges (MMRs): technical/building-blocks/merkle-mountain-ranges.md
      - Merkle Proof: technical/building-blocks/merkle-proof.md
      - Switch Commitments: technical/building-blocks/switch-commitments.md
    - Blockchain and Consensus:
      - Coinbase Maturity Rule: technical/blockchain-and-consensus/coinbase-maturity-rule.md
      - Fast Sync: technical/blockchain-and-consensus/fast-sync.md
      - Proof-of-Work: technical/blockchain-and-consensus/proof-of-work.md
      - Pruning Blockchain Data: technical/blockchain-and-consensus/pruning-blockchain-data.md
      - State and Storage: technical/blockchain-and-consensus/state-and-storage.md
    - Miscellaneous:
      - Contracts: technical/miscellaneous/contracts.md
      - Dandelion: technical/miscellaneous/dandelion.md
      - Range Proofs Format: technical/miscellaneous/range-proof-format.md

